# Generated by scripts/packaging.js from plugin/bin/manifest.env - do not edit.
# CodeEraser 1.7.3: every url is a release asset, every sha256 the pin release.yml verified before publishing.
class Codeeraser < Formula
  desc "Erase LLM-induced code & document entropy"
  homepage "https://codeeraser.dev"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.3/ce-1.7.3-aarch64-macos"
      sha256 "56c31be8acda069e946826603da14017f7e41d4fedd98783d0d1791d8abd0080"
    end
    on_intel do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.3/ce-1.7.3-x86_64-macos"
      sha256 "7fd6933aad6c3fe80459f60256dedccb1cc54d63e611e81f753e1ebd6e75f101"
    end
  end
  on_linux do
    on_intel do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.3/ce-1.7.3-x86_64-linux"
      sha256 "9e5413b03b19aee4060c87687ed8063775b965d933370c4b1786dc91395d1dd7"
    end
    on_arm do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.3/ce-1.7.3-aarch64-linux"
      sha256 "a13f071e04c10184749e2fa946ca14117acf5e2edd046240008dcf8b95247361"
    end
  end

  resource "ce-core" do
    on_macos do
      on_arm do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.3/ce-core-1.7.3-aarch64-macos"
        sha256 "315e3a36355fcbbbc9adf11b4ff28397f4a23239b9365b138528cfd21e4d8a49"
      end
      on_intel do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.3/ce-core-1.7.3-x86_64-macos"
        sha256 "76e911f5354f89aecc539307931bd9fbdf6912692f0f852e73b388335b9ed115"
      end
    end
    on_linux do
      on_intel do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.3/ce-core-1.7.3-x86_64-linux"
        sha256 "d18bbcdd5cfb3bfcfeaa4a8976fb2496afd335934a503597bccf612976a869d6"
      end
      on_arm do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.3/ce-core-1.7.3-aarch64-linux"
        sha256 "d68617d9dc7ff76045209027e4c19bf9c3cf7565af508cc292d3fc1a72a07f33"
      end
    end
  end

  def install
    bin.install Dir["ce-#{version}-*"].fetch(0) => "ce"
    resource("ce-core").stage { bin.install Dir["ce-core-#{version}-*"].fetch(0) => "ce-core" }
    # a raw release binary lands 0644 (curl) and the cleaner keeps only the x bit it finds
    chmod 0755, [bin/"ce", bin/"ce-core"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ce --version")
  end
end
