# Generated by scripts/packaging.js from plugin/bin/manifest.env - do not edit.
# CodeEraser 1.7.4: every url is a release asset, every sha256 the pin release.yml verified before publishing.
class Codeeraser < Formula
  desc "Erase LLM-induced code & document entropy"
  homepage "https://codeeraser.dev"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.4/ce-1.7.4-aarch64-macos"
      sha256 "d4021643f0791ae9980257419193c60ba34471bc5a87c2135ffbccf651f2d888"
    end
    on_intel do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.4/ce-1.7.4-x86_64-macos"
      sha256 "383fcaad4dce7a2e0421bf739d6707b380713009f8fabddcd81b9e2ec6d6f268"
    end
  end
  on_linux do
    on_intel do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.4/ce-1.7.4-x86_64-linux"
      sha256 "2495d39c9b440f0439630af380429a1055ffe3a6e3d4d11de16a79c5f20e637e"
    end
    on_arm do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.4/ce-1.7.4-aarch64-linux"
      sha256 "46a5e8b7b5dbd325d5d8520c734dc663760fa115fa71b99ae87547d3e29cda97"
    end
  end

  resource "ce-core" do
    on_macos do
      on_arm do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.4/ce-core-1.7.4-aarch64-macos"
        sha256 "eea9c7dcad6c1efaa73ff933d17caf64e55f5d3916f53c29a58ba481dd907e93"
      end
      on_intel do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.4/ce-core-1.7.4-x86_64-macos"
        sha256 "11052986fc6571c176cc9943d0d9b705d898a9865d51eeed6230aa4609b6fd8c"
      end
    end
    on_linux do
      on_intel do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.4/ce-core-1.7.4-x86_64-linux"
        sha256 "b1df917fa009f21c0831215af0301ca68d737655ef3d8374bbbeda2828e7f481"
      end
      on_arm do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.4/ce-core-1.7.4-aarch64-linux"
        sha256 "f2ec83118bbecef246ecd932c442bb8726063d6c88a88203287988756f5d182e"
      end
    end
  end

  def install
    bin.install Dir["ce-#{version}-*"].fetch(0) => "ce"
    resource("ce-core").stage { bin.install Dir["ce-core-#{version}-*"].fetch(0) => "ce-core" }
    # a raw release binary lands 0644 (curl) and the cleaner keeps only the x bit it finds
    chmod 0755, [bin/"ce", bin/"ce-core"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ce --version")
  end
end
