# Generated by scripts/packaging.js from plugin/bin/manifest.env - do not edit.
# CodeEraser 1.7.2: every url is a release asset, every sha256 the pin release.yml verified before publishing.
class Codeeraser < Formula
  desc "Erase LLM-induced code & document entropy"
  homepage "https://codeeraser.dev"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.2/ce-1.7.2-aarch64-macos"
      sha256 "a25078a0b678face41f7ef01615e5c535c85c3dee73f8c3626888f2e19e75475"
    end
    on_intel do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.2/ce-1.7.2-x86_64-macos"
      sha256 "f5930a620ca8cd5d1269b06ebef81b15d31420b37c9395d674f25d904d8b5bd2"
    end
  end
  on_linux do
    on_intel do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.2/ce-1.7.2-x86_64-linux"
      sha256 "c3d95f08e7d25ac30e5135e81eb9ae9e2a74d53780725a44d14500059d73241a"
    end
    on_arm do
      url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.2/ce-1.7.2-aarch64-linux"
      sha256 "045d632a8ebcb2b9344fb48eca8316a8aa34178109488378dd27ff3d9610ff1b"
    end
  end

  resource "ce-core" do
    on_macos do
      on_arm do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.2/ce-core-1.7.2-aarch64-macos"
        sha256 "9816cb08f22cac2e0e778a56623f2a0239bb763ba181d7117fa7f67add9fc2ca"
      end
      on_intel do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.2/ce-core-1.7.2-x86_64-macos"
        sha256 "3cd991b3c17df7f3755b91153d029532bb7eaa64a1d4f6e445bac54672d92b50"
      end
    end
    on_linux do
      on_intel do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.2/ce-core-1.7.2-x86_64-linux"
        sha256 "9773a29240bd1223e579a6cc07bf81cc2e3331ba8b1ed7e8c1485fc7dc226aa9"
      end
      on_arm do
        url "https://github.com/skymanbp/CodeEraser/releases/download/v1.7.2/ce-core-1.7.2-aarch64-linux"
        sha256 "08569605802e9e3d64e1580b9ced69494c8df42bdcbd135ab7bb2535df98dd16"
      end
    end
  end

  def install
    bin.install Dir["ce-#{version}-*"].fetch(0) => "ce"
    resource("ce-core").stage { bin.install Dir["ce-core-#{version}-*"].fetch(0) => "ce-core" }
    # a raw release binary lands 0644 (curl) and the cleaner keeps only the x bit it finds
    chmod 0755, [bin/"ce", bin/"ce-core"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ce --version")
  end
end
